app = "mastodon"

kill_signal = "SIGINT"
kill_timeout = 5

[env]
  LOCAL_DOMAIN = "pumpitbetter.com"
  WEB_DOMAIN = "social.pumpitbetter.com"
  RAILS_ENV = "production"
  RAILS_LOG_TO_STDOUT = "enabled"
  WEB_CONCURRENCY = "1"
  REDIS_HOST = "mastodon-redis.internal"
  REDIS_PORT = "6379"
  S3_ENABLED = true
  S3_BUCKET = "pumpitbetter-mastodon"
  # S3_ALIAS_HOST=files.example.com
  SMTP_SERVER = "smtp.mailgun.org"
  SMTP_PORT = "587"
  SMTP_FROM_ADDRESS="support@pumpitbetter.com"

  # THESE ARE SECRETS:
  # SMTP_LOGIN=<Your Login here>
  # SMTP_PASSWORD=<Your password here>

# [mounts]
#   processes = ["rails"]
#   source = "mastodon_uploads"
#   destination = "/opt/mastodon/public/system"

[processes]
  rails = "bundle exec rails s -p 8080"
  sidekiq = "bundle exec sidekiq"

[[statics]]
  guest_path = "/opt/mastodon/public"
  url_prefix = "/"

[[services]]
  internal_port = 8080
  processes = ["rails"]
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

  [[services.http_checks]]
    path = "/health"
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
